version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "964:964"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app/backend
      - backend_node_modules:/app/backend/node_modules
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "198:198"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: npm run dev

volumes:
  backend_node_modules:
  frontend_node_modules:
